### ISSUE TITLE
Wireshark dissector not updated

### ISSUE THREAD

**Issue by arenantonio92** [iotaledger/iota-wireshark-dissector#5]
Hi, I'm trying to use this Wireshark dissector, but I couldn't see any message sent from/to my full node.  
I saw that from iri-1.8.0 gossip transactions have dynamic length, so the Lua script does not process any message. 
Is there a way to solve this problem? Thanks.

**Comment by GalRogozinski** [comment]
You are correct

The maintainer of the dissector has left so it wasn't updated...
I guess we are waiting for community contributions now, because I am not seeing this tool becoming a priority for my team anytime soon...

**Comment by arenantonio92** [comment]
Thanks for you answer.
I would like to contribute to update the tool, however I haven't found any documentation about gossip transaction management in iri. 
Can you help to found out any documentation, that is not simply  and brutally reading the iri source code.

**Comment by GalRogozinski** [comment]
Hey,
The  best thing we currently have are the google doc:
https://docs.google.com/document/d/1WJy-es3CxdMobafrnF3-BlSIPJPZ5cGcsXjCNCyt7SE/edit?usp=sharing

https://docs.google.com/document/d/13XHSVo44oy8MvY0-fSzT-SQ2JZ8fIE7B7-VV02dTQeI/edit?usp=sharing

We need to create more proper docs out of them.
Feel free to use this issue to ask me any questions you like :-)

**Comment by arenantonio92** [comment]
Thanks for sharing these documents. However, I cannot access to the second google doc :(
Do you need my email address for sharing it ?

**Comment by GalRogozinski** [comment]
I edited the link, is it better now?

**Comment by arenantonio92** [comment]
Unfortunately no.. google doc asks me for an authorization for reading the second document you linked.
I required with my account antonio.arena@ing.unipi.it but still no access :(

**Comment by GalRogozinski** [comment]
Edited again and invited you by mail

**Comment by arenantonio92** [comment]
Perfect, I can access. Thank you!!
